// code generated by ---ChatGPT---
const express = require('express');
const { trimFields, nonEmpty } = require('../middleware/validate');
const authController = require('../controllers/authController');

const router = express.Router();

router.post(
  '/login',
  trimFields('email', 'password'),
  nonEmpty('email', 'Email is required.'),
  nonEmpty('password', 'Password is required.'),
  authController.login
);

router.post('/logout', authController.logout);

module.exports = router;
