// code generated by ---ChatGPT---
module.exports = {
  requireAuth(req, res, next) {
    if (!req.session.user) {
      res.flash('warning', 'Please log in first.');
      return res.redirect('/#home');
    }
    return next();
  },
  requireAdmin(req, res, next) {
    if (!req.session.user || req.session.user.role !== 'admin') {
      res.flash('danger', 'Admin access required.');
      return res.redirect('/#home');
    }
    return next();
  }
};
