// code generated by ---ChatGPT---
module.exports = {
  nonEmpty(fieldName, message) {
    return (req, res, next) => {
      if (!req.body[fieldName] || !String(req.body[fieldName]).trim()) {
        res.flash('danger', message || `${fieldName} is required.`);
        return res.redirect('back');
      }
      req.body[fieldName] = String(req.body[fieldName]).trim();
      return next();
    };
  },
  trimFields(...fields) {
    return (req, _res, next) => {
      fields.forEach((field) => {
        if (Object.prototype.hasOwnProperty.call(req.body, field) && typeof req.body[field] === 'string') {
          req.body[field] = req.body[field].trim();
        }
      });
      next();
    };
  }
};
