// code generated by ---ChatGPT---
const bcrypt = require('bcrypt');
const User = require('../models/userModel');

function attachSessionUser(req, user) {
  req.session.user = {
    id: user.id,
    email: user.email,
    display_name: user.display_name,
    role: user.role
  };
}

exports.login = async (req, res, next) => {
  try {
    const { email, password } = req.body;
    const user = await User.findByEmail(String(email).trim());

    if (!user) {
      res.flash('danger', 'Invalid credentials.');
      return res.redirect('/#home');
    }

    const ok = await bcrypt.compare(String(password), user.password_hash);
    if (!ok) {
      res.flash('danger', 'Invalid credentials.');
      return res.redirect('/#home');
    }

    attachSessionUser(req, user);
    res.flash('success', `Welcome back, ${user.display_name}!`);
    return res.redirect('/#home');
  } catch (err) {
    return next(err);
  }
};

exports.logout = (req, res) => {
  req.session.destroy(() => {
    res.redirect('/#home');
  });
};
